### ISSUE TITLE
Getting Null Reference when trying to run in Unity

### ISSUE THREAD

**Issue by mklewandowski** [zenith4eva/GS2UNITY#1]
Hi!  Does this package still work?  I followed the steps:
- made a Google Sheet
- added the provided code to Apps Scripts
- deployed the and set access to anyone
- copied the deployment ID
- opened project in Unity 2021
- entered the deployment ID in the Google Sheets DB script in the Demo scene
- added my Sheet to the Sheet tab names in the Google Sheets DB script in the Demo scene

When I run in Unity, I get the following:
"NullReferenceException: Object reference not set to an instance of an object" at Assets/Plugins/GS2Unity/GoogleSheet.cs line 189.

I also notice that if I return to Google Sheets and run the code snippet (https://gist.github.com/zenith4eva/5204d88714a73dbf74e4ad9bff061fe4) in Apps Scripts I get the following:
"TypeError: Cannot read property 'parameter' of undefined" at this line:
`sheetNameString = e.parameter.sheetNameString;`

Any thoughts on what might be happening?  Thanks!

**Comment by zenith4eva** [comment]
Hi Matt! I just checked using 2021.3.4f1 that it was working. Would you be able to try again? I can help you debug once I'm more free later this week if you would like.
![image](https://user-images.githubusercontent.com/2201032/173687533-d8ff4e30-af47-4d80-a8f4-8c1de14c98f8.png)

**Comment by mklewandowski** [comment]
I went through the steps again and got it working.  I will close.  Thanks!
